### createCategory
POST {{API_HostAddress}}/Category/
Content-Type: application/json

{
  "categoryName": "TestCategory4",
  "isActive": true,
  "description": "Category3 description",
  "Author": "Tester"
}

> {%
    client.global.set("new_category_id", response.body.id);
    client.log("Created Category ID: " + client.global.get("new_category_id"));
%}

### getAllCategories
GET {{API_HostAddress}}/Category/
Accept: application/json

### getCategoryByID
GET {{API_HostAddress}}/Category/{{new_category_id}}/
Accept: application/json

### editlCategory
PUT {{API_HostAddress}}/Category/{{new_category_id}}/
Content-Type: application/json

{
  "categoryName": "TestBestCategory",
  "isActive": false,
  "description": "Category Description",
  "author": "Toaster"
}

### deleteCategory
DELETE {{API_HostAddress}}/Category/{{new_category_id}}/
Accept: application/json