### createProductGroup
POST {{API_HostAddress}}/ProductGroup/
Content-Type: application/json

{
  "name": "TestProductGroup6",
  "isActive": true,
  "note": "ProductGroup1 description",
  "author": "Test",
  "categoryId": 13013
}

> {%
    client.global.set("new_product_group_id", response.body.id);
    client.log("Created Category ID: " + client.global.get("new_product_group_id"));
%}

### getAllProductGroups
GET {{API_HostAddress}}/ProductGroup/
Accept: application/json

### getProductGroupByID
GET {{API_HostAddress}}/ProductGroup/{{new_product_group_id}}/
Accept: application/json

### editlProductGroup
PUT {{API_HostAddress}}/ProductGroup/{{new_product_group_id}}/
Content-Type: application/json

{
  "name": "QuestProductGroup",
  "isActive": false,
  "note": "ProductGroup description",
  "author": "Test"
}