@new_product_id = 16228

### createProduct
POST {{API_HostAddress}}/Product/
Content-Type: application/json

{
  "sku": "SKU332",
  "title": "Best Test",
  "shortDescription": "The Best Test",
  "vendorId": 111,
  "productTypeId": 111,
  "unitMeasureId": 111,
  "currencyId": 111,
  "productGroupId": 111,
  "quantityMin": 11110,
  "quantityMax": 100,
  "startDate": "2024-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": false,
  "isTop": false,
  "isNew": false,
  "logo": "http://example.com/logo.png",
  "author": "Te1ter"
}

> {%
    client.global.set("new_product_id", response.body.id);
    client.log("Created Product ID: " + client.global.get("new_product_id"));
%}

### getAllProducts
GET {{API_HostAddress}}/Product/
Accept: application/json

### getPaginatedProducts
GET {{API_HostAddress}}/Product/catalog
Accept: application/json

### getProductByID
GET {{API_HostAddress}}/Product/162045/
Accept: application/json

### updateProduct
PUT {{API_HostAddress}}/Product/{{new_product_id}}/
Content-Type: application/json

{
  "sku": "SKU123-UPDATED",
  "title": "Test Product Updated",
  "shortDescription": "A test product updated",
  "vendorId": 5026,
  "productTypeId": 4012,
  "unitMeasureId": 4012,
  "currencyId": 2009,
  "productGroupId": 3039,
  "quantityMin": 1,
  "quantityMax": 100,
  "startDate": "2023-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": true,
  "isTop": true,
  "isNew": true,
  "logo": "http://example.com/logo.png",
  "author": "Tester"
}

### patchProduct
PATCH {{API_HostAddress}}/Product/{{new_product_id}}/
Content-Type: application/json

{
  "sku": "SKU321-PATCHED",
  "title": "Quest Product Updated",
  "shortDescription": "A test product updated twice",
  "isPromo": false,
  "startDate": "2024-01-01T00:00:00Z",
  "endDate": "2024-12-31T23:59:59Z"
}

### createPrice
POST {{API_HostAddress}}/Product/15/price
Content-Type: application/json

{
  "Price": 100,
  "TermDuration": "123",
  "BillingPlan": "TestBillingPlan",
  "CountryCode": "TST",
  "Segment": "TestSegment",
  "startDate": "2023-01-01T00:00:00Z"
}

> {%
    client.global.set("new_price_id", response.body.id);
    client.log("Created Price ID: " + client.global.get("new_price_id"));
%}

### editPrice
PUT {{API_HostAddress}}/Product/{{new_product_id}}/price/{{new_price_id}}/
Content-Type: application/json

{
  "Price": 100,
  "TermDuration": 10,
  "BillingPlan": "QuestBillingPlan",
  "CountryCode": "TST",
  "Segment": "QuestSegment",
  "startDate": "2023-01-01T00:00:00Z"
}

### getProductByID
GET {{API_HostAddress}}/Product/10/
Accept: application/json

### deletePrice
DELETE {{API_HostAddress}}/Product/{{new_product_id}}/price/{{new_price_id}}/
Content-Type: application/json

### addTag
POST {{API_HostAddress}}/Product/10/tag/1/
Content-Type: application/json

### deleteTag
DELETE {{API_HostAddress}}/Product/10/tag/1/
Content-Type: application/json

### deleteProduct
DELETE {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json
