### createProduct
POST {{API_HostAddress}}/Product/
Content-Type: application/json

{
  "sku": "SKU332",
  "title": "Best Test",
  "shortDescription": "The Best Test",
  "vendorId": 1,
  "productTypeId": 1,
  "unitMeasureId": 1,
  "currencyId": 1,
  "productGroupId": 1,
  "quantityMin": 1,
  "quantityMax": 100,
  "startDate": "2023-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": false,
  "isTop": false,
  "isNew": false,
  "logo": "http://example.com/logo.png",
  "author": "Tester"
}

> {%
    client.global.set("new_product_id", response.body.id);
    client.log("Created Product ID: " + client.global.get("new_product_id"));
%}

### getAllProducts
GET {{API_HostAddress}}/Product/
Accept: application/json

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### updateProduct
PUT {{API_HostAddress}}/Product/{{new_product_id}}/
Content-Type: application/json

{
  "sku": "SKU123-UPDATED",
  "title": "Test Product Updated",
  "shortDescription": "A test product updated",
  "vendorId": 1,
  "productTypeId": 1,
  "unitMeasureId": 1,
  "currencyId": 1,
  "productGroupId": 1,
  "quantityMin": 1,
  "quantityMax": 100,
  "startDate": "2023-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": false,
  "isTop": true,
  "isNew": true,
  "logo": "http://example.com/logo.png",
  "author": "Tester"
}

### patchProduct
PATCH {{API_HostAddress}}/Product/{{new_product_id}}/
Content-Type: application/json

{
  "sku": "SKU321-PATCHED",
  "title": "Quest Product Updated",
  "shortDescription": "A test product updated twice",
  "productTypeId": 2
}

### deleteProduct
DELETE {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json
