services:
  licensenexus.api:
    image: licensenexus.api
    container_name: licensenexus_api
    build:
      context: .
      dockerfile: LicenseNexus.API/Dockerfile
    ports:
      - "5000:8080" # HTTP
      - "5001:8081" # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoArchDatabase=Server=mssql;Database=LicenseNexus_Minimal_Db;User Id=sa;Password=TST12345!;TrustServerCertificate=True;
      - ConnectionStrings__RedisArchDatabase=Server=mssql;Database=LicenseNexus_Full_Db;User Id=sa;Password=TST12345!;TrustServerCertificate=True;
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=LicenseNexus_Mongo
      - RedisSettings__ConnectionString=redis:6379
    depends_on:
      - mssql
      - mongo
      - redis
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: licensenexus_mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TST12345!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  mongo:
    image: mongo:latest
    container_name: licensenexus_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis/redis-stack-server:latest
    container_name: licensenexus_redis
    command: redis-stack-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - mssql
      - mongo
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://licensenexus_redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis

  mongo-exporter:
    image: percona/mongodb_exporter:0.49.0
    container_name: mongo_exporter
    restart: unless-stopped
    command:
      - '--mongodb.uri=mongodb://licensenexus_mongo:27017'
      - '--compatible-mode'
      - '--collect-all'
    ports:
      - "9216:9216"
    depends_on:
      - mongo

  mssql-exporter:
    image: awaragi/prometheus-mssql-exporter:latest
    container_name: mssql_exporter
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SERVER=licensenexus_mssql
      - PORT=1433
      - USERNAME=sa
      - PASSWORD=TST12345!
    ports:
      - "4000:4000"
    depends_on:
      - mssql

volumes:
  mssql_data:
  mongo_data:
  redis_data: