@API_HostAddress = http://localhost:5000/api

POST {{API_HostAddress}}/Category/
Content-Type: application/json

{
  "categoryName": "Category3",
  "isActive": true,
  "description": "Category3 Description",
  "author": "test"
}

###
GET {{API_HostAddress}}/Category/
Accept: application/json

###
GET {{API_HostAddress}}/Category/1/
Accept: application/json

###
POST {{API_HostAddress}}/Currency/
Content-Type: application/json

{
  "LiteralCode": "$",
  "Name": "Dollar",
  "CountryCode": "USA"
}

###
GET {{API_HostAddress}}/Currency/
Accept: application/json

###
GET {{API_HostAddress}}/Currency/1/
Accept: application/json

###
POST {{API_HostAddress}}/ProductType/
Content-Type: application/json

{
  "TypeName": "TestType"
}

###
GET {{API_HostAddress}}/ProductType/
Accept: application/json

###
GET {{API_HostAddress}}/ProductType/1/
Accept: application/json

###
POST {{API_HostAddress}}/UnitMeasure/
Content-Type: application/json

{
  "Name": "TestUnitMeasure"
}

###
GET {{API_HostAddress}}/UnitMeasure/
Accept: application/json

###
GET {{API_HostAddress}}/UnitMeasure/1/
Accept: application/json

###
POST {{API_HostAddress}}/Product/
Content-Type: application/json

{
  "sku": "SKU123",
  "title": "Test Product",
  "shortDescription": "A test product",
  "vendorId": 1,
  "productTypeId": 1,
  "unitMeasureId": 1,
  "currencyId": 1,
  "productGroupId": 1,
  "quantityMin": 1,
  "quantityMax": 100,
  "startDate": "2023-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": false,
  "isTop": true,
  "isNew": true,
  "logo": "http://example.com/logo.png",
  "author": "Tester"
}

###
GET {{API_HostAddress}}/Product/
Accept: application/json

###
GET {{API_HostAddress}}/Product/3/
Accept: application/json

###
PUT {{API_HostAddress}}/Product/3/
Content-Type: application/json

{
  "sku": "SKU123-UPDATED",
  "title": "Test Product Updated",
  "shortDescription": "A test product updated",
  "vendorId": 1,
  "productTypeId": 1,
  "unitMeasureId": 1,
  "currencyId": 1,
  "productGroupId": 1,
  "quantityMin": 1,
  "quantityMax": 100,
  "startDate": "2023-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": false,
  "isTop": true,
  "isNew": true,
  "logo": "http://example.com/logo.png",
  "author": "Tester"
}

###
DELETE {{API_HostAddress}}/Product/3/
Accept: application/json

###
