@API_HostAddress = http://localhost:5000/api

### createProduct
POST {{API_HostAddress}}/Product/
Content-Type: application/json

{
  "sku": "SKU123",
  "title": "Best Test",
  "shortDescription": "The Best Test",
  "vendorId": 8,
  "productTypeId": 1,
  "unitMeasureId": 1,
  "currencyId": 1,
  "productGroupId": 1,
  "quantityMin": 1,
  "quantityMax": 100,
  "startDate": "2023-01-01T00:00:00Z",
  "endDate": "2023-12-31T23:59:59Z",
  "isPromo": false,
  "isTop": false,
  "isNew": false,
  "logo": "http://example.com/logo.png",
  "author": "Tester"
}

> {%
    client.global.set("new_product_id", response.body.id);
    client.log("Created Product ID: " + client.global.get("new_product_id"));
%}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### editlVendor
PUT {{API_HostAddress}}/Vendor/8/
Content-Type: application/json

{
  "name": "QuestVendor1",
  "originalName": "Vendor1",
  "description": "Vendor1 description",
  "countryCode": "TST",
  "logo": "123123123"
}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### editlCategory
PUT {{API_HostAddress}}/Category/1/
Content-Type: application/json

{
  "categoryName": "QuestCategory1",
  "isActive": true,
  "description": "Category1 Description",
  "author": null
}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### editProductGroup
PUT {{API_HostAddress}}/ProductGroup/1/
Content-Type: application/json

{
  "name": "QuestGroup1",
  "isActive": true,
  "note": "ProductGroup1 description",
  "author": "Test"
}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### editProductType
PUT {{API_HostAddress}}/ProductType/1/
Content-Type: application/json

{
  "typeName": "QuestType"
}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### editlUnitMeasure
PUT {{API_HostAddress}}/UnitMeasure/1/
Content-Type: application/json

{
  "name": "QuestUnitMeasure"
}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### editlCurrency
PUT {{API_HostAddress}}/Currency/1/
Content-Type: application/json

{
  "literalCode": "?",
  "name": "QuestDollar",
  "countryCode": "USA"
}

### getProductByID
GET {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json

### deleteProduct
DELETE {{API_HostAddress}}/Product/{{new_product_id}}/
Accept: application/json
